### ISSUE TITLE
making it work with React

### ISSUE THREAD

**Issue by mezod** [pfzero/justifiedGallery#1]
Hello, I am trying to figure out how to make it work with React but there's too little documentation and I am having a hard time understanding everything I need to do to get it to work, is there any way I can contact you? Any directions would be very welcome! Thanks :)

**Comment by ErhanAbi** [comment]
Hi @mezod, I am working on providing an usage (with live demo) example of this package. I didn't created a react component for using it yet (it's on roadmap), but, I can still provide an example with only vanilla js. Expect it to be ready this week (I am kind of busy these days). I hope it's not going to be too late...

**Comment by mezod** [comment]
hey @pfzero thanks for your reply! Meanwhile I am working on a simple version, but I'd be glad to see the docs/demo/react component once it's done! No hurries! Thanks

**Comment by ErhanAbi** [comment]
@mezod I have added a link to a working [demo](http://j.mp/justifiedGrid). Also, the demo is hosted on requirebin so you have full access to the code - which is now vanillla javascript.

**Comment by ErhanAbi** [comment]
Also, regarding the react version of this module, I'm not sure at the moment of this. Because people will generally want to have extra content on each image (image title with link and so on), will want to have applied special effects when hovering the image, e.t.c. Also, they might want to also have a (big) image gallery version where each image is displayed at high resolution. There are quite a lot of things that needs to be taken into consideration, and I personally don't quite like the all-in-one version of a component, that will cover all the use cases and introduces bloated functionalities. Having only this module separately gives the maximum flxibility.

At most, a minimal demo with react can be added from which developers can add more functionalities.
